"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

interface Load {
  id: string;
    created_at: string;
      escort_type: string;
        rate: number;
          status: string;
            origin_city?: string;
              origin_state?: string;
                dest_city?: string;
                  dest_state?: string;
                  }

                  export default function OpenLoadsBoard() {
                    const [loads, setLoads] = useState<Load[]>([]);
                      const [loading, setLoading] = useState(true);

                        useEffect(() => {
                            const fetchLoads = async () => {
                                  try {
                                          const supabase = createClient(
                                                    process.env.NEXT_PUBLIC_SUPABASE_URL || "",
                                                              process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""
                                                                      );

                                                                              const { data, error } = await supabase
                                                                                        .from("loads")
                                                                                                  .select("*")
                                                                                                            .eq("board_type", "open-loads")
                                                                                                                      .eq("status", "open");

                                                                                                                              if (error) {
                                                                                                                                        console.error("Error fetching loads:", error);
                                                                                                                                                } else {
                                                                                                                                                          setLoads(data || []);
                                                                                                                                                                  }
                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                console.error("Fetch error:", err);
                                                                                                                                                                                      } finally {
                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                    }
                                                                                                                                                                                                        };

                                                                                                                                                                                                            fetchLoads();
                                                                                                                                                                                                              }, []);

                                                                                                                                                                                                                if (loading) {
                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                          <div style={{ padding: "20px", textAlign: "center" }}>
                                                                                                                                                                                                                                  Loading...
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                if (loads.length === 0) {
                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                          <div style={{ padding: "20px", textAlign: "center" }}>
                                                                                                                                                                                                                                                                  No loads posted yet.
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                    <div style={{ padding: "20px" }}>
                                                                                                                                                                                                                                                                                          <h1>Open Loads Board</h1>
                                                                                                                                                                                                                                                                                                <div style={{ marginTop: "20px" }}>
                                                                                                                                                                                                                                                                                                        {loads.map((load) => (
                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                              key={load.id}
                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                      padding: "15px",
                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "4px",
                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong>Route:</strong> {load.origin_city}, {load.origin_state} →{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {load.dest_city}, {load.dest_state}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>Escort Type:</strong> {load.escort_type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Rate:</strong> ${load.rate.toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong>Posted:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {new Date(load.created_at).toLocaleDateString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }