"use client"
import { useState } from "react"
import { supabase } from "@/lib/supabase"

const PRICES = {
  member:      "price_1TF00LLmfugPCRbAl6sF0Oup",
    pro:         "price_1TF021LmfugPCRbA7CGgLhC0",
      pevo_member: "price_1TF0D4LmfugPCRbAd4hMO22R",
        pevo_pro:    "price_1TF0DiLmfugPCRbAPWsN2K5x",
          bgc:         "price_1TF0EILmfugPCRbAvM6Q5rhW",
          }
          
          async function startCheckout(priceId: string, setLoading: (v: string) => void) {
            setLoading(priceId)
              try {
                  const { data: { session } } = await supabase.auth.getSession()
                      if (!session) { window.location.href = "/signin?redirect=pricing"; return }
                          const res = await fetch("/api/checkout", {
                                method: "POST",
                                      headers: { "Content-Type": "application/json" },
                                            body: JSON.stringify({ priceId, userId: session.user.id }),
                                                })
                                                    const { url, error } = await res.json()
                                                        if (error) { alert("Error: " + error); return }
                                                            window.location.href = url
                                                              } catch (e) {
                                                                  alert("Checkout failed")
                                                                    } finally {
                                                                        setLoading("")
                                                                          }
                                                                          }
                                                                          
                                                                          export default function PricingPage() {
                                                                            const [loading, setLoading] = useState("")
                                                                              return (
                                                                                  <div style={{ maxWidth: 1100, margin: "0 auto", padding: "48px 20px" }}>
                                                                                        <h1 style={{ textAlign: "center", fontSize: 32, fontWeight: 800, marginBottom: 8 }}>Membership &amp; Access</h1>
                                                                                              <p style={{ textAlign: "center", color: "var(--t2)", marginBottom: 48, fontSize: 16 }}>Simple, transparent pricing. No hidden fees.</p>
                                                                                              
                                                                                                    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 24, marginBottom: 40 }}>
                                                                                                    
                                                                                                            {/* Free Trial */}
                                                                                                                    <div style={{ background: "var(--p2)", border: "1px solid var(--l2)", borderRadius: 12, padding: "28px 24px" }}>
                                                                                                                              <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Free Trial</h2>
                                                                                                                                        <div style={{ fontSize: 32, fontWeight: 800, color: "var(--or)", marginBottom: 4 }}>$0</div>
                                                                                                                                                  <p style={{ fontSize: 12, color: "var(--t2)", marginBottom: 20 }}>No credit card required</p>
                                                                                                                                                            <ul style={{ listStyle: "none", padding: 0, margin: "0 0 24px", display: "flex", flexDirection: "column", gap: 10 }}>
                                                                                                                                                                        {["Create your profile", "See load boards (blurred)", "Preview all tools", "No bidding or contact info"].map(f => (
                                                                                                                                                                                      <li key={f} style={{ fontSize: 13, color: "var(--t1)", display: "flex", gap: 8, alignItems: "flex-start" }}><span style={{ color: "var(--or)" }}>+</span>{f}</li>
                                                                                                                                                                                                  ))}
                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                      <button onClick={() => window.location.href = "/join"} style={{ width: "100%", background: "var(--l2)", color: "var(--t1)", border: "none", borderRadius: 6, padding: "10px 0", fontWeight: 700, fontSize: 14, cursor: "pointer" }}>Get Started</button>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                      {/* Member */}
                                                                                                                                                                                                                                              <div style={{ background: "var(--p2)", border: "2px solid var(--or)", borderRadius: 12, padding: "28px 24px", position: "relative" }}>
                                                                                                                                                                                                                                                        <span style={{ position: "absolute", top: -12, left: 20, background: "var(--or)", color: "#000", fontSize: 10, fontWeight: 800, padding: "3px 10px", borderRadius: 99 }}>MEMBER</span>
                                                                                                                                                                                                                                                                  <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Member</h2>
                                                                                                                                                                                                                                                                            <div style={{ fontSize: 32, fontWeight: 800, color: "var(--or)", marginBottom: 4 }}>$19.99<span style={{ fontSize: 14, fontWeight: 400, color: "var(--t2)" }}>/mo</span></div>
                                                                                                                                                                                                                                                                                      <p style={{ fontSize: 12, color: "var(--t2)", marginBottom: 20 }}>For escorts ready to compete</p>
                                                                                                                                                                                                                                                                                                <ul style={{ listStyle: "none", padding: 0, margin: "0 0 24px", display: "flex", flexDirection: "column", gap: 10 }}>
                                                                                                                                                                                                                                                                                                            {[
                                                                                                                                                                                                                                                                                                                          "Full load board access (60s after Pro)",
                                                                                                                                                                                                                                                                                                                                        "Bid on loads",
                                                                                                                                                                                                                                                                                                                                                      "See carrier contact info",
                                                                                                                                                                                                                                                                                                                                                                    "Push notifications",
                                                                                                                                                                                                                                                                                                                                                                                  "Permit directory - all 50 states",
                                                                                                                                                                                                                                                                                                                                                                                                "Reviews system"
                                                                                                                                                                                                                                                                                                                                                                                                            ].map(f => (
                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={f} style={{ fontSize: 13, color: "var(--t1)", display: "flex", gap: 8, alignItems: "flex-start" }}><span style={{ color: "var(--or)" }}>+</span>{f}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => startCheckout(PRICES.member, setLoading)} disabled={loading === PRICES.member} style={{ width: "100%", background: "var(--or)", color: "#000", border: "none", borderRadius: 6, padding: "10px 0", fontWeight: 700, fontSize: 14, cursor: "pointer", opacity: loading === PRICES.member ? 0.6 : 1 }}>{loading === PRICES.member ? "Loading..." : "Subscribe"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Pro */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ background: "var(--p2)", border: "2px solid #f59e0b", borderRadius: 12, padding: "28px 24px", position: "relative" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ position: "absolute", top: -12, left: 20, background: "#f59e0b", color: "#000", fontSize: 10, fontWeight: 800, padding: "3px 10px", borderRadius: 99 }}>PRO</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Pro</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontSize: 32, fontWeight: 800, color: "#f59e0b", marginBottom: 4 }}>$29.99<span style={{ fontSize: 14, fontWeight: 400, color: "var(--t2)" }}>/mo</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: 12, color: "var(--t2)", marginBottom: 20 }}>For power escorts who move loads fast</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul style={{ listStyle: "none", padding: 0, margin: "0 0 24px", display: "flex", flexDirection: "column", gap: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Instant load access - 60s head start",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "SMS alerts when loads drop",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "SMS load posting - text to post",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Deadhead Minimizer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Escort Availability Board",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Fleet Manager - up to 5 escorts",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "First cert verification free",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Priority listing + invoice generator"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ].map(f => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={f} style={{ fontSize: 13, color: "var(--t1)", display: "flex", gap: 8, alignItems: "flex-start" }}><span style={{ color: "#f59e0b" }}>+</span>{f}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => startCheckout(PRICES.pro, setLoading)} disabled={loading === PRICES.pro} style={{ width: "100%", background: "#f59e0b", color: "#000", border: "none", borderRadius: 6, padding: "10px 0", fontWeight: 700, fontSize: 14, cursor: "pointer", opacity: loading === PRICES.pro ? 0.6 : 1 }}>{loading === PRICES.pro ? "Loading..." : "Go Pro"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Carrier */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ background: "var(--p2)", border: "1px solid var(--l2)", borderRadius: 12, padding: "28px 24px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Carrier</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 32, fontWeight: 800, color: "#4ade80", marginBottom: 4 }}>Free<span style={{ fontSize: 14, fontWeight: 400, color: "var(--t2)" }}> always</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ fontSize: 12, color: "var(--t2)", marginBottom: 20 }}>Post loads, find escorts fast</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ul style={{ listStyle: "none", padding: 0, margin: "0 0 24px", display: "flex", flexDirection: "column", gap: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Post unlimited loads",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "All 3 load boards",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "FMCSA verified badge",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Permit directory",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Carrier dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ].map(f => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li key={f} style={{ fontSize: 13, color: "var(--t1)", display: "flex", gap: 8, alignItems: "flex-start" }}><span style={{ color: "#4ade80" }}>+</span>{f}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => window.location.href = "/join?role=carrier"} style={{ width: "100%", background: "var(--l2)", color: "var(--t1)", border: "none", borderRadius: 6, padding: "10px 0", fontWeight: 700, fontSize: 14, cursor: "pointer" }}>Sign Up Free</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* BGC Badge */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ maxWidth: 480, margin: "0 auto", background: "var(--p2)", border: "1px solid var(--l2)", borderRadius: 12, padding: "28px 24px", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ fontSize: 11, fontWeight: 700, background: "#1e3a5f", color: "#60a5fa", padding: "3px 10px", borderRadius: 99 }}>BACKGROUND CHECK</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 10, marginBottom: 4 }}>BGC Badge</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ fontSize: 13, color: "var(--t2)", maxWidth: 300 }}>One-time background check. Admin reviews manually. Badge appears on your profile upon approval.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ textAlign: "right" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontSize: 28, fontWeight: 800, color: "var(--t1)" }}>$9.99</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontSize: 12, color: "var(--t2)", marginBottom: 12 }}>one-time</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => startCheckout(PRICES.bgc, setLoading)} disabled={loading === PRICES.bgc} style={{ background: "#1e3a5f", color: "#60a5fa", border: "none", borderRadius: 6, padding: "10px 28px", fontWeight: 700, fontSize: 15, cursor: "pointer", opacity: loading === PRICES.bgc ? 0.6 : 1 }}>{loading === PRICES.bgc ? "Loading..." : "Get BGC Badge"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }"